version: "3.8"

services:
  file-management-service:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./data:/tmp/my-root
    environment:
      - JAVA_OPTS
    command: java $JAVA_OPTS -jar app.jar
