replicaCount: 1

image:
  repository: jacket629/file-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  springProfile: prod
  javaOpts: "-Xms256m -Xmx512m"

persistence:
  enabled: true
  mountPath: /tmp/my-root
  size: 1Gi
  storageClass: ""

config:
  applicationYaml: |
    spring:
      application:
        name: filesystem
    server:
      port: 8081
    fileservice:
      rootFolder: /tmp/my-root

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60

serviceAccount:
  create: false
  name: my-file-service-account
