replicaCount: 1

image:
  repository: jacket629/file-service
  tag: 2.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  javaOpts: "-Xms256m -Xmx512m"

persistence:
  mountPath: /tmp/my-root
  size: 1Gi
